apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverb
  labels:
    app: reverb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverb
  template:
    metadata:
      name: reverb
      labels:
        app: reverb
    spec:
      containers:
        - name: reverb
          image: uber_eat_api_image
          command: [ 'php', 'artisan', 'reverb:start', '--debug' ]
          ports:
            - name: main
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: uber-eat-api-secret