apiVersion: batch/v1
kind: CronJob
metadata:
  name: uber-eat-api-scheduler
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: registry-secret
          containers:
            - name: main
              image: uber_eat_api_image
              command: [ 'sh', '-c', 'php artisan schedule:run >> /dev/null 2>&1' ]
              envFrom:
                - secretRef:
                    name: uber-eat-api-secret
          restartPolicy: Never
