apiVersion: v1
data:
    APP_DEBUG: ENC[AES256_GCM,data:I+rR5xjsI0g=,iv:LeGlMe/fo54NDih3uSZYa5OSKhaH3Vzto4UdKE6ZxUw=,tag:jgsGFh/zwC2lLyvl4gTMjQ==,type:str]
    APP_ENV: ENC[AES256_GCM,data:4jzqCfChuj+l2sp8n2l/gw==,iv:q57nkiWbAD5WZshng3ELKhr4MHRd2K2XBd9B4kdFl0A=,tag:b37ImBE+jGA2ldq0vDlqpw==,type:str]
    APP_FAKER_LOCALE: ENC[AES256_GCM,data:FJ60chtZx5E=,iv:8erfFzNLcjxgwUlwfD47FQ2Wry3RjFYM3apQoxkQ030=,tag:WacgoXDVeu6gwMjR6n5m7g==,type:str]
    APP_FALLBACK_LOCALE: ENC[AES256_GCM,data:66hP5w==,iv:Hbar7HS5NyxGSQKGlr46+dcezhzIYcFHIxxc/pdCzcc=,tag:eECIbP/UwKBxDaa3Ro4fKA==,type:str]
    APP_KEY: ENC[AES256_GCM,data:Q+YwSKA3BTCl6k+m24ck0vGC9y3D32UjmEG9NpuVRefNkXVSa05te5DfTcKLn4hzTQJVOMjtBXaFNcNF2hrLTeM2bnU=,iv:zG0bxUJQz9NfyPLdz2Uox0pftO+DCsY/51HhHvQE4cI=,tag:2ns5zs2dp0cxgq6WqTuozw==,type:str]
    APP_LOCALE: ENC[AES256_GCM,data:voniWw==,iv:wET+PAlyyRfjYFxfYln8bsCfoKOUPTzGgn/RTQpu/UA=,tag:CE7kE23VqE1bC17qeIJDsg==,type:str]
    APP_MAINTENANCE_DRIVER: ENC[AES256_GCM,data:X5OF/V49yQQ=,iv:A7OPYKXeb7vIstGcy80PxdzSr2oeCsU2cuxYHcaYFMw=,tag:v/d8s6Yx+Qfs5y9IXy9ITQ==,type:str]
    APP_MAINTENANCE_STORE: ENC[AES256_GCM,data:+Zjrw9uywRE=,iv:J2RbDWWz3kfqF2GXtzyhQDsPxXl8x71K2jKb3qxFC1s=,tag:u2aPr/uAAbw3t2yan7/T7A==,type:str]
    APP_NAME: ENC[AES256_GCM,data:FdRmlEowMUrCu8pt,iv:CTz/UwCga0xBQSJvSniGnLM8BfKfY1laXe/6dfr5vLM=,tag:cLZx7FyPXmnx760WoS4f1w==,type:str]
    APP_TIMEZONE: ENC[AES256_GCM,data:xj5u8A==,iv:OAzrDhmL+ABPKOTyscrPOWwRUwuAKaZ5qfmzAFpAxcs=,tag:ge/qiRq76kd91V0ph6ahgw==,type:str]
    APP_URL: ENC[AES256_GCM,data:BY9bL3DrtFxs5ccNmzqP5rYVKK6MXRTBF75Fa4EaQqaEWVsEDHY1j5kTGYfriY26UH/1gH9K/oWcPGDXGD+5gO2GSmM=,iv:43ovIx0Ykg7GW29I7Tcnwi5XDey7DCae629n7TgpXV4=,tag:BNrpa0AorZ0FwwPVTyAHrA==,type:str]
    BCRYPT_ROUNDS: ENC[AES256_GCM,data:WsV3CQ==,iv:u4qO/aQiypo1I4LeWfnJCyLk9/HHwfXcIc46S+RXKQ8=,tag:5ipbS8D0l6YtUfW9Rj4Lpw==,type:str]
    BROADCAST_CONNECTION: ENC[AES256_GCM,data:PXD2TRjF1rI=,iv:m2HDhWYMpEbW68s/TjmdJ9QwQ0bZIs/lgHEzc70p7eY=,tag:Blloxx4P6zfG/306+C0HJw==,type:str]
    CACHE_PREFIX: ""
    CACHE_STORE: ENC[AES256_GCM,data:2v/AyXLHK+A=,iv:oQa3P4rgNxFF+EM8urwI5SX/OI0VPlZWl3DMFCmSnhk=,tag:jg4rp3Fak3hBdl7pkU8x0g==,type:str]
    CASHIER_CURRENCY: ENC[AES256_GCM,data:N8bROw==,iv:ZuCSrxWHlEZi4rdzaE/hPc3mTd8JrmYZsQQku+URSKg=,tag:MSFqR5zJCU0LCGpVOrJ2+g==,type:str]
    CASHIER_CURRENCY_LOCALE: ENC[AES256_GCM,data:h1mo0I7nC+g=,iv:LWwB26rS5GXf0ye6ZTKvyv6SaNG6Kt5f5xk3q9uSpxc=,tag:msAy7rtRT3EcgExeuu+U2w==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:DnE1naue8RY=,iv:53ZynUK89Mp1hMemsNaSgaXnKPLV/oL9RwjN1sNO8a4=,tag:URdkOieADurL/4WszdzmGQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:z3GSEG25dCeXmQ1faOPHjQ==,iv:rRR3q4IwzZJu2C6qKIFCGQ/ESOA61pKCLJNNBRNWdtI=,tag:9aFFvc2POsc20HsNceWYzQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:qE77BJIoXvO7BMf0mU53vmgZziNYXv8pFxuwh59Ao9xrV016GN2c8Nk7LPJNQ6cx,iv:9rpmPO44OdLe/EzpiAYFDKMpw2De9JLh0o0CIae5bAM=,tag:EHs5fevBZCVLqfDCCZjd0A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Jvj4W5QLkkU32jmuyDPNDg==,iv:uHfhxCUX8LeN1pmfM5UlhCld/+HyluWSSzIJ4YETKKY=,tag:ioYOB4Xd7fN/oEaoKHNpEA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:6QXmm92OVbQ=,iv:Xoo6d3sMJDjiqflUMNUKXkJ/81BHOSjAFlb1Wfg76NQ=,tag:2umSX0x7VXxcxUtUEyXgwg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:44zFpxkr0HT2+o9k,iv:xvqAXTvC2ITTx0KoF8REXhS/y56ISNqRLN1h7Yq5oAw=,tag:j4YALL+NMZ3ibJQ6kQh+ow==,type:str]
    FILESYSTEM_DISK: ENC[AES256_GCM,data:EcKA50oiGVU=,iv:OK5iU6JGE3B1ff6aw5tcbtT7X/5M9vEJfUR58/2v30o=,tag:/AgFr1sNK5FcLVP0h39vWA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:pXXx7fNzUpz2duAbz3muyXjysGj9aRa8pK5EUNwCYJ2U3GG5DzvO3uN9swdXBai8IZt/k2bktNTcXJwfOnzvtloxKpxrmeE7uUzPokUB/dXSIPFRr9Z6TQ==,iv:cNqug3SJ2TG/ZOeVF3ElptxG5XTGy0lj75a7iWAb0RQ=,tag:7JmnBXwYXhLezDgLzvtjXQ==,type:str]
    LOG_CHANNEL: ENC[AES256_GCM,data:MbAgP0+cdsw=,iv:b9Ei5G+i2TvjjQQ2HMGP0p86purnN6AhNlY4hVjPO6w=,tag:vhQXM/bhQE7EW6LYLyfGEQ==,type:str]
    LOG_DEPRECATIONS_CHANNEL: ENC[AES256_GCM,data:1kFRPiI5q/c=,iv:oA7OlpoOTkv5veerdCc2Cs9ndRxMPjcXUj2JG2P6gFg=,tag:orpx/k2HBroOGPY503jfmQ==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:EUgVCTkwZM8=,iv:p+n3qZHEe2LCKNqP1mPww6X3w4Ckvl/uC2NFB1iJFe8=,tag:m+Z+VniKM4IEI9Nt+eH0zA==,type:str]
    LOG_STACK: ENC[AES256_GCM,data:0ljzUCUfrZNlM4ETJgGOmxlswVM=,iv:HNNQWAGAg5A3lUklYMO5L2Bg/N3a2j0gwaHjslxDZl8=,tag:NgEGrxe+vzYHg6LQoH64zw==,type:str]
    LOGO_DEV_TOKEN: ENC[AES256_GCM,data:Yb6XlPo25ig2AuXO1gvmGPdHXuF/zN3jhC3i5+/lTc+7uQm1,iv:hgsF+KPt4tKqaoyYQAvV/WU+WG8fZs9Hzm3gDUDqfYI=,tag:HljRvJzUdcZfYPLbatjf1w==,type:str]
    MAIL_FROM_ADDRESS: ""
    MAIL_FROM_NAME: ""
    MAIL_HOST: ""
    MAIL_MAILER: ENC[AES256_GCM,data:NWAvpp0SlU0=,iv:QBZTozdHHNJlfM/zEA+9GmKMY488chCx1Pi7lTFLgPQ=,tag:JsrpQNILxhJ3f8dnFSI4JQ==,type:str]
    MAIL_PASSWORD: ""
    MAIL_PORT: ENC[AES256_GCM,data:to7gQg==,iv:WWsDy/GrigLVl/schYO+7jo2Qh8MQjCXd3OlonQ/stY=,tag:wMoGPsa1O/tT8yvtCsNx/Q==,type:str]
    MAIL_USERNAME: ""
    PHP_CLI_SERVER_WORKERS: ENC[AES256_GCM,data:swFIMQ==,iv:D5BYIILCzFlggnPI7w1AuYvyUgvInmLm2ZVNt9H+fLw=,tag:8+Rd77UFkLkfKMPLVCfJzw==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:iyKwNup94sM=,iv:pGtxZ6R8sehWbDOFHV3w0MBo2q3+9CeD09E79VAz15A=,tag:muA/a0hTOs/bW9gFHPeuaQ==,type:str]
    REDIS_CLIENT: ENC[AES256_GCM,data:yqfpsgYjyvDAuS2R,iv:sbw1+AD8LciQrsm3dQZSBIvxO5EmM2GI/uzYKRIydMM=,tag:E0YNSUnS8/sEMX7gmLIibA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:f0AsXFXhzSjTr1cdqTO+ywgBFmdWYtufjdzbAfHEHMZKH0pfA8wxPZoTIuA=,iv:Lvp4UGiGFEFe1HRLPZCRooto6nqIsviTKkRHZnas4+Q=,tag:vhkXkVLlleqijd8ITPDrrA==,type:str]
    REDIS_PASSWORD: ""
    REDIS_PORT: ENC[AES256_GCM,data:ey005z+URuw=,iv:mSn27dqJDgFgRegphrUXrIKJIQrYNUcDdCPeJc5Jg2o=,tag:NNb8KgIdXZHQQFl9mqKjAw==,type:str]
    REDIS_PREFIX: ENC[AES256_GCM,data:yDeU4/7iLeQ=,iv:mXyHfUKD1a5NAT98L0EPu59J7UNPQPgny5yfW9Kqmlc=,tag:xoCML/dAm/4iNh/duNl99g==,type:str]
    SESSION_DOMAIN: ENC[AES256_GCM,data:+xCprmF2dbA=,iv:PhPrEZwe/KnMUHhDliI+DuaHqxWszGm53j/tke53B4I=,tag:RL3Qf5VBBtLNR4qqDQHWVA==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:LB7QqaDyUhE=,iv:8aa5ET3+rDcqupm1CnOtf0L2Q45Jj1bj/5pV3xCHg9E=,tag:L0QSvb4BzVd+FKHEBY9jnQ==,type:str]
    SESSION_ENCRYPT: ENC[AES256_GCM,data:ZCWWQh/75GM=,iv:xp45z075ldLcbfOyVl0cD+P+Hf5UTGOtllxybxrcR94=,tag:3rQxmPCgYOm53RM1kPceOA==,type:str]
    SESSION_LIFETIME: ENC[AES256_GCM,data:xKX0lA==,iv:ohuL3E03k093VL2zC+DpQwJXO71WPYZRmmJ4d9J04eE=,tag:S5tLEBO33dfdRZWpES+7Gg==,type:str]
    SESSION_PATH: ENC[AES256_GCM,data:t43blQ==,iv:h7Pvy9e6I5jzTxMA8lS4iI1W+MFwYMHijOHp+5FtDXk=,tag:H42VYcwb9CFCs7sIIEzGdA==,type:str]
    REVERB_APP_ID: ENC[AES256_GCM,data:elQBfd5HLMw=,iv:Aq4vBZDAvVQ/I6V6cusUgpTucYT9w9nuc6HXpf7g+b0=,tag:ybAlaRKfcLJsPDa6Xl9EdA==,type:str]
    REVERB_APP_KEY: ENC[AES256_GCM,data:W2V9mw3K/7ObO+w1UcvT4rA3wkBX1Q0MQfKsqw==,iv:6/bA1CPJQJwRZJRenQbBD4xyEMo/23K0ArK4Nvyl9tw=,tag:ZCrMAGwTRtSKrdhiDETowQ==,type:str]
    REVERB_APP_SECRET: ENC[AES256_GCM,data:28t36pc1GV1RdUL6Ok7JdxF4kDN8Z516Oaie7A==,iv:5Ya1PCZkrQ9GFbcpX6hDSITdzvkBuNBU8+nq59OkI/k=,tag:wTyyOSsn6Lf0lirJYsFMng==,type:str]
    REVERB_HOST: ENC[AES256_GCM,data:AqZIo0c2HKFFX30EwHtUz/hoiPA0skxh7UcpuaGwPL+4wttJPSVAAG9tAmW8AF/1P55ARn9dXyM=,iv:98CJMHhbN2wfDMtgonpAzSOkCLt+BD4l7uma1wyBiEQ=,tag:3+KCr7BpKYcZHlDtiQ0izA==,type:str]
    REVERB_PORT: ENC[AES256_GCM,data:IPbbN0yykTI=,iv:yKxn78q1+odarfBTpfzFoNydTQCmO5NpMqX9yQgpB0c=,tag:2zQU8MlYX0SUgFphR5a3Qg==,type:str]
    REVERB_SCHEME: ENC[AES256_GCM,data:+HrBimrCybo=,iv:tznCekh0e79hjWJrC6aS2h98Nn9woZ4coziYVLOvRnw=,tag:v8pb1wlXF62ZyADnXcVuUw==,type:str]
kind: Secret
metadata:
    name: uber-eat-api-secret
sops:
    age:
        - recipient: age1ann3qhr9jkn9m8y3tkl8qwg6ederfanhtdqk8g2x5893548wt9ls6877ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTWpmalRLNk5XRUFOamxO
            QndCK05YREYyYVcrc1RvYVk5KzVCVVZTdFE0CldrOG5qOExmYmtDWVJJV1B0WU00
            TERSd01SY0srQ21oclBUc2x3U01xdUkKLS0tIGdWVE1aYzBmbG1OaEUrczVxVE9x
            d2dDS3hueEk0cEtuRzNseERYTmZxS1EKzXYkygfpAPA16vQx2rKoRPL09md79aEm
            GAAG0VHEC4tC6ewwvtytSI9U3HUQE6F1G0rYsWYLhAK/zSZFOVwjFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rnvd2ad92af4p70ap6wvevjuhstt9k9ucdrzz5v9pd03wu30uacs3f7v60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYjZLREZsSTZtVHdlbk9X
            aFFCS0lqeWY0T3huTzhkb3RaZStOeVJkaWgwCkNUaGRjODlneGR4MnNMWnY4Y2s5
            dW9Hd2Nyd3ZTRU5tR2QvN2RIbTZrY1kKLS0tIEQxQnBBNmtKWFpicFE2WHNveU9l
            YmYyNnk2V1ZIcDA4OEliamJXME0zNWcKtWWlHbEJzJAZaYkj6GzrwddBN/5lxRlK
            nesLLCQ/vrUfaSCCngd8b4jk632tYfJI2jngTVaQ8Vp8V4zCE6BlOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T08:44:32Z"
    mac: ENC[AES256_GCM,data:MJm12y8jgAAOgB4ZUmEHwMjSFR2WSb4nRiZ6m+qhDjHxSEmMjWkZDbfWcbUSTbUHaMHVVpRIzcSGs6NX0ZipnvmgBlaT8RgYI8Qp+iebjbYisgt6LqmWdtgYtucNO2V6A4nh/BD1sMwOb2+5EZ6AVgR19rHtTp5sJvc4M7Lh6JU=,iv:dKbLMLFJETJfZt6DWIqfT2BxtyH0BTg0vdjYu34gs/Q=,tag:/QeHTPjNgEOSs+Mpt5aorQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
