apiVersion: v1
data:
    APP_DEBUG: ENC[AES256_GCM,data:8r5tPixCM5M=,iv:U+ZWMS7vMZUrReaOgq11xXAigr8RWCqBfBzWAAEp4as=,tag:istRtF7EhrQNY3mleHPbzw==,type:str]
    APP_ENV: ENC[AES256_GCM,data:blFsD9R8WwSlJXT8n5xBZw==,iv:xtS398gQKMu+xAX4wRTvP679cqOo/olUwU8NO5pHWOA=,tag:+hKa0ApvjmtLF/r0pxGIzw==,type:str]
    APP_FAKER_LOCALE: ENC[AES256_GCM,data:z9B/Eha6DJ8=,iv:CZz34MHLr6AB6oiO21hizeIlbGpt888LnoRjXzz+z9A=,tag:e6sV+WyrxX0YeTbANp6jNQ==,type:str]
    APP_FALLBACK_LOCALE: ENC[AES256_GCM,data:8x2B4A==,iv:DZq9xP0Dqi+5ju11FS+oSsHK2yzVeTbAY8EpDYZB+xs=,tag:GHMY/qWthQhemZLTyV9wrQ==,type:str]
    APP_KEY: ENC[AES256_GCM,data:N+qVITJYAl89iGNsy4GgfOHOFX+ihfSYpkK6+MtyTH383yKyT8pyAzIMqxZW50Ojeq++O0pREgtSA9+OeVKwQMwAwVc=,iv:HQ7lRylf+IorAld045qWl+ynVvzHXCizbN14YCrTweM=,tag:e27O0J0yRpXEi0u068h9dg==,type:str]
    APP_LOCALE: ENC[AES256_GCM,data:OujGZA==,iv:gDWc50HdnMGqZ4wUhs5IoAmgwuLzkWRQ56N/JNuzJKY=,tag:gK2GizxKUS9NqXTg5BA3Kw==,type:str]
    APP_MAINTENANCE_DRIVER: ENC[AES256_GCM,data:lsyRhEPvm5U=,iv:bFksgj9sAYhCust7sbP1RNpNZaLhFuzj+nD0JXffNeA=,tag:Fy+QhwGxBiQvslHBV2xyLA==,type:str]
    APP_MAINTENANCE_STORE: ENC[AES256_GCM,data:+9BX81CW3JI=,iv:1f97PiNI0G9u9kwAtfqkyELN64P3u8Jl1b/ALigu7Rw=,tag:vMUJ1rxhJZ+0yHvxC7oYoQ==,type:str]
    APP_NAME: ENC[AES256_GCM,data:/vkTkkJPRnI+d+DX,iv:spQdHNScjqrJT9xQMUTXbx0J47pfurXMqKaNCmNN23E=,tag:f9YgHnO+g4IAZrTi97riJQ==,type:str]
    APP_TIMEZONE: ENC[AES256_GCM,data:IZpCxQ==,iv:NntRRKYYl1lvobfToGo9jYW6yEy78jZmFcLBsIevo4s=,tag:C1QXerG9tQFchBxiPAUvuQ==,type:str]
    APP_URL: ENC[AES256_GCM,data:7OT7etMebw9MTUUrLWO26ty7ziAfJPBsVPzTrGOaSv8TP256241U49aID/350nrXDIHdw+kg2ec0d+2RIF7zPOhCg+c=,iv:egDsiKMN0ig15Fft9c2oZtGiyaP6K5EjxyaA4BCJsN4=,tag:IB43IckMyZBbLKWSZtukhA==,type:str]
    BCRYPT_ROUNDS: ENC[AES256_GCM,data:VceUiQ==,iv:m8xaqLm/A2DE7Avh9YHqmj2MLwJzJ29OhXl3T7T3ZHI=,tag:PHjTGkDpBl+mYmwKvupbKQ==,type:str]
    BROADCAST_CONNECTION: ENC[AES256_GCM,data:lNshCmub7rg=,iv:9wfObpPc7z43uqWZaR7abjMyLMTKSM2rwYXJyObcpQ8=,tag:OuVWAGtikaHUq/YRhOWkpQ==,type:str]
    CACHE_PREFIX: ""
    CACHE_STORE: ENC[AES256_GCM,data:6BUyFUlMmLA=,iv:t/E8y2Gcpyc7mA2wByg22fX1C4PDxdsPxES96h2+140=,tag:yUg3fnrHEkMw2QoZYvV/fw==,type:str]
    CASHIER_CURRENCY: ENC[AES256_GCM,data:dbSaSQ==,iv:w2LcxUf0mcBaSe878NfNTpwltpIR3neG+PbuD/CPVik=,tag:anmRcVqWZqy1d75+IrsHVQ==,type:str]
    CASHIER_CURRENCY_LOCALE: ENC[AES256_GCM,data:JnXaAeRAUMk=,iv:kmge3k66ijiaTEQmpwXMiEa0+73+cN7fVTmIWCdOGfM=,tag:7pS68LPupBMC1Ja5oYmcJw==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:jq0J3uRxAW8=,iv:EGYapQP7cKtlgjdPSOGIEszUs/OKfzd1f8X8wIp7Rm0=,tag:XhJCTOx5PrfU0Xqo8SvwwQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:2XPGkO+jwTeQawWCqlMJXQ==,iv:LIY7SDvtxJNIxWLo3dTkhspTCAEvaGWnK21UXBUxpus=,tag:m93cv4bcyjQpf6JTgby4dA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:Tq9Aj2RlGuwPZvRlCpg3tKNkQDL8neWy9eKcDcPXCA3CX9Uy4wkuLaC38JVT4NvD,iv:aXaEMSJvNuu2qavzdBm5D4Fny9lcsi5NQec7tErDmVU=,tag:TjinW9Ee5sxtiOjUDKCGew==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:FOfVZMZ+OwALCLqUJJSFVw==,iv:0IttouDycsDxxip/1ulWb0kMTYyrLSw4/3QCbx0O7aU=,tag:8OaFmF92N1hEda44e8aKtw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:E5S2Hs9w+HU=,iv:0d4Q1XcSz8BB43vriySZaaCL9Yp/kqCx1xZu68LmNJQ=,tag:5EuJR2pra1VUmqbirPnWPA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:6ljDIx3TYiARhlt9,iv:7Q/9hgBLhKC+wrGMMjDLTayt5uqkl7ukvW2jIh/519Y=,tag:LWi3p2u6akTT6cxWebPhdg==,type:str]
    FILESYSTEM_DISK: ENC[AES256_GCM,data:Uf8l5/p9kc8=,iv:5HivKbw7Y1zc6ZqxzlkufBbyirHU9Kheid1T3h633WM=,tag:xZtdt8nKF1nomniAFaURPA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:RRP91mQkgHCC59bAZaASJGZ0s0iNKH0JwdkTO3uE2wHXNf6yyo7EnZ5LbDqMbxWRm0CDC32ptfet4PwRE8Tc+6NuqJA5gMOeCrZjEBlgczYe8FGghx+iqA==,iv:ZOfjljwQtUs/F4WFaZAkgT0K2GLahm5vnyLdGcwVI/k=,tag:QElr7amqBjTUGpOCtHw3Lw==,type:str]
    LOG_CHANNEL: ENC[AES256_GCM,data:PW67dVhwras=,iv:l5b3+1mOo3OX2wzEa9n/Pfp7VE0dzyEnYWZsCxyzkSo=,tag:x6zbsUKZNeX1h4QIv/qrKw==,type:str]
    LOG_DEPRECATIONS_CHANNEL: ENC[AES256_GCM,data:KiSPZGrGHNo=,iv:wHBFUF7MMTtjA7vdM45+coSNodfNkmXrJ49qEROknJk=,tag:t4YF9X0/rs/DWYHNbDpyoA==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:BjR/54nWtBE=,iv:0w6AmWA2yNBpV7nkta1o01pNGPPszXYbRlpV/WZDC9E=,tag:O3cBeFp+hHc2JgzT3YyEKQ==,type:str]
    LOG_STACK: ENC[AES256_GCM,data:xWili+VbybBINJhq+RdoTALvpnE=,iv:imAsSYZWeEs57HmX4ADlBBXcAp0Yoyw1hihH2WgJvDc=,tag:WU4UeKYNWwx7D4lYrpiAVw==,type:str]
    LOGO_DEV_TOKEN: ENC[AES256_GCM,data:MvEfXjJ3dGO6XYi5nOV+wWREbf7E8K13bNpxJwjp9AVr1fQ7,iv:TsmHkqT2nGF/S+xblpnJaJEgbMggVD/ruYld4xYQLm4=,tag:2EszqK43ZYfaPM0QAGoWuA==,type:str]
    MAIL_FROM_ADDRESS: ""
    MAIL_FROM_NAME: ""
    MAIL_HOST: ""
    MAIL_MAILER: ENC[AES256_GCM,data:U53MgMsgMa8=,iv:FZGWLY+OyXjj5k6vuBqaXzcPdPHmuZClEBuL5OWiuzo=,tag:ae3l+s8+XCC5yduN4ilQIg==,type:str]
    MAIL_PASSWORD: ""
    MAIL_PORT: ENC[AES256_GCM,data:3ARkDA==,iv:rjP1NS2RjCR5vtxZIvU2HJkBmDjVCL+BeO6B+whatHI=,tag:keqKYD7+bRskDsLlWgNniQ==,type:str]
    MAIL_USERNAME: ""
    PHP_CLI_SERVER_WORKERS: ENC[AES256_GCM,data:7U3xoA==,iv:M5Mbh2MBOyqstjSWLNnFM8uoPPDfWNViQEWADpbd9Y8=,tag:MBvY4j0fTifmfAlrmm5+Yg==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:FlSNv7GKIsk=,iv:RCiIkOg1R1i7UaU+SvkJLnWYbVnINf+C7kjqUqu76h0=,tag:D+Je1wGjdXYETeTWmJVuDA==,type:str]
    REDIS_CLIENT: ENC[AES256_GCM,data:zOfNktqnYAiMJNYx,iv:LJtwErwklbb5UeboKU3vftJlGjyzE/JwrbViPaBdn2M=,tag:16DRzMv1y/cXOevSjK1Ukw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:ItmuXr3tbq3p9vV/qWTdAGznMjRV3OEffKcUJDvfD/kRnGayuNXaUag8xEc=,iv:Ir+vnOQ7gxL7TJWYpLatp6SSPym8LiWUwWttHhyLdSU=,tag:Z4HaVk6gUtTvEnxTksoQDA==,type:str]
    REDIS_PASSWORD: ""
    REDIS_PORT: ENC[AES256_GCM,data:FGf/QyqURbA=,iv:zPre5hu4HB6jiu7Ims+P896rtb+0CKv+ZDKG6kJmq7A=,tag:AreuhavG7AWW9+E+2UrbqQ==,type:str]
    REDIS_PREFIX: ENC[AES256_GCM,data:f5TRCUz+Jho=,iv:K3gm19f8p5X4nu/AB0y1EmyKljxK9734NX89xS6Df/c=,tag:eJJEPJycyddyqvGotePUTw==,type:str]
    SESSION_DOMAIN: ENC[AES256_GCM,data:ohIFK/Km5b8=,iv:wsp47N7AiH/JK6L3Y5WEzEsaI2wb73hKq4EPM3DF6jI=,tag:4pMKdfUzS5kdfkDg1zcwhw==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:m/6nzak0ms4=,iv:p1VvRyr9HuDoTlvWdSa2jkOz7AqpgnriokFNO8xPBdw=,tag:PE+wyJbq7/jli71Xta9Zzw==,type:str]
    SESSION_ENCRYPT: ENC[AES256_GCM,data:5Ne/u4YWgJk=,iv:iMKvlBgsDS7PEWbhjNJ0wrwO2OYRtMOdHdoAUs6/4qk=,tag:O33xlJCzPHX1u211+u/r1Q==,type:str]
    SESSION_LIFETIME: ENC[AES256_GCM,data:auT1dA==,iv:IoOxhdk5iJ5J+BR3TkCfUu0zxXXOBxvx23HmipbzU4c=,tag:FKqttZyv4Iqk/dFrVGZ0sg==,type:str]
    SESSION_PATH: ENC[AES256_GCM,data:VByk7A==,iv:lJUBNdqxoPs6HFtPOrG4xT89xxe9l++sfVm0Tq5WTvA=,tag:fKIVdqzoUvwKPzS4Z5atjA==,type:str]
    REVERB_APP_ID: ENC[AES256_GCM,data:1sNaGVIyi5E=,iv:WT6QWQZQr8DTdsCnyY4SEWlRZMddXWY1sVO7wiRX2WA=,tag:xnAcZSGneuQuTVUG7joJFA==,type:str]
    REVERB_APP_KEY: ENC[AES256_GCM,data:ybyu8Dkdb8MeUjBp2tf5HkfRJ68tpGmA4QB3PA==,iv:DFXuHyftnXEoa0G5zfZNEiidLJZlIXFPLb2de6w8Ou0=,tag:Hy8ekb0IiovoVMOVtza9Eg==,type:str]
    REVERB_APP_SECRET: ENC[AES256_GCM,data:2EBU1RUCqEF1TyY/h1TObf0MF/YOvxK+RWki8A==,iv:g5+PqwhbgVL926Ee07uHX05/L3FrexOVIuSwQR/FwjU=,tag:lA9xvIiawQ3Cw2lkPhXdoQ==,type:str]
    REVERB_HOST: ENC[AES256_GCM,data:yNKoYILlSMyUz3ov1Rv0F/9ZNb2xXFeRAin2uCq/T/wBR+h88LY0+0LjuBibIL9EATZBmRtqqdY=,iv:8Hut7XEcNBmI3JyrutopufzFpTJKzk+RB+WYOborLUM=,tag:MPLh+TtXJfNNCelRcm/SeQ==,type:str]
    REVERB_PORT: ENC[AES256_GCM,data:kpjLNIRyQQ==,iv:u5Q0VshsNZ8xXJyQjhpuqds0bv0EA+hkQEmZodbNs8c=,tag:jOLlapIWdxs5NdKbCqFpuQ==,type:str]
    REVERB_SCHEME: ENC[AES256_GCM,data:cnNHL/VKmA==,iv:mVRfknP3T6PACIQw90FbLcEMvkepWh4NoXjHry9OO4c=,tag:Slh7+B3Ceytq4ekihtJLuA==,type:str]
kind: Secret
metadata:
    name: uber-eat-api-secret
sops:
    age:
        - recipient: age1ann3qhr9jkn9m8y3tkl8qwg6ederfanhtdqk8g2x5893548wt9ls6877ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UEVRT1lJVXhTVWRHZGZk
            b3hpc1M3ZFg3dXplMG9JaWkzZmt2RHd3NWpjCjRyN3doalA1SGRTaTRZR21PdktR
            MFJiSk9jYkpvakl4WWk3L2dPRHM2Y3cKLS0tIFh1ZHlzZ2V4amJlZGdZbmZuSndV
            N0d3aExhTzhqMDJLYWdBNTVEVUlYR2sK++m1153ukZvl3uN03PL0950p/cC3QtkA
            7Ht9q0onefR/pAWEuOLSbwAeh6yib+jpQT4J4xUvB3mnf2OWhskwBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rnvd2ad92af4p70ap6wvevjuhstt9k9ucdrzz5v9pd03wu30uacs3f7v60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVllMay8xb1dSaGpsL1ps
            ZnVHVi9VdzlMaWZ3SENFRDk0RlluK3NYNTFvCnNxUE9VSjg5NStscVJJdkd3ejdy
            eUxtS3YwbUF3SHhNU1FSWnFDYXhPM2MKLS0tIFpodGRIR3Yya0R3UFVhTlYveVg3
            REZQSXFwdUNHaFZvaWdBbmE1cmFHQmsKxAj1eP1c0RdSi/GN4pf0/xV5mkQayK54
            KbZx3bZOJt/TCVDc72aJJ43lW8u5Tmy+xHqAK5IUFA0/3b7lOf3a5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T08:34:56Z"
    mac: ENC[AES256_GCM,data:YlldOTVbzV14YUOktoYniN5Fi7lOzmsJJ0gyFtS5jqQ4oQes+QqDwIj91hTotlkmmK3LxqXhrFuGJ0WrBIIdj1/vTcI4hl9E1S3Kpq+RQesKihDZ2itpBuhNnd6jox/1/S1mSLln5X+3jLnKLkauBXay/RCFiHlai2Ien2L7oYw=,iv:su0rDcSM8OzmVUTPNUcWMLvK1yanFOxSIspWg3Efvk4=,tag:0XYcjpzpOHALhukfo9eRBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
