apiVersion: v1
data:
    APP_DEBUG: ENC[AES256_GCM,data:sQJRA0O/jLI=,iv:EsHX/ZdEXsayIlSGfhdRxxxSBu2HgSKfSzWpo08rHIY=,tag:9tPl+qwa/WVR9/G/nXTJDA==,type:str]
    APP_ENV: ENC[AES256_GCM,data:QzxH4l8lazpiGsBvBnBFSA==,iv:SgeJEFGfZiyfjiBfaRaxCQ8ukRkgAVZaK8WRKvu+MRU=,tag:RH9ZkG/JXlYUDLl/5FkxXg==,type:str]
    APP_FAKER_LOCALE: ENC[AES256_GCM,data:DlY0K/ARuME=,iv:LBxOJQ+epdf3xIv2L4ocrq7VgjZctMEqht3EmAq8rR8=,tag:YQmShSa2FbdoyH3plYh99Q==,type:str]
    APP_FALLBACK_LOCALE: ENC[AES256_GCM,data:w5Cbpg==,iv:gZBomY+EyghIp+iN1/OJsDOvf/jofl3JrgyZRuSuIdU=,tag:MKtSka7Qmsj3BRv3BE8uPg==,type:str]
    APP_KEY: ENC[AES256_GCM,data:k0sxQOR6dDHXKxDgvjR67RlNXw9M0Yd2G8DhylVRGtghfA6mDkSqM6uu/wjf4tvrxEwjMnlRDvarYaB+chFdi2XRrQs=,iv:Kjr3d4mqhqXmutcK+7mUphxsrSqVb7M27tne40zLiZ4=,tag:bL6EbCU9jsm5b06uz/Y+3g==,type:str]
    APP_LOCALE: ENC[AES256_GCM,data:IUkAZg==,iv:vIu5yJtOGm7GlZahsd9u3sABRXzUSgflULvzbftoHA8=,tag:OHgzYRqC8v27Ea96dXVHzw==,type:str]
    APP_MAINTENANCE_DRIVER: ENC[AES256_GCM,data:XbXtQm8YoUo=,iv:X6i4dpE1LLoJWa346KK2PyZO2mAZTS+dA5lxvH+9tUE=,tag:PtBg3JPiLbrP67oonOovSw==,type:str]
    APP_MAINTENANCE_STORE: ENC[AES256_GCM,data:AT7Oc31AHCA=,iv:neXNgQOuraXRmY0tQLUNUE3xmg4h9mrMhKeOtMtX8dM=,tag:JvzYdOpLj3TBl5rk+39v+w==,type:str]
    APP_NAME: ENC[AES256_GCM,data:NQGWrLIXY2XEMI1Y,iv:WsgizOJww2UiHnhWPn/tfNL7mEuirvsj0N2wp7n5Ljs=,tag:o+ueqPQinLtr829ntWaEVA==,type:str]
    APP_TIMEZONE: ENC[AES256_GCM,data:mbLCxg==,iv:dv0W37TFNt6DIlZ3ImDlNBxDeyEZPrTXuzvhzFsKeKg=,tag:6b+ggiVrjRnA4OaMq3S0zg==,type:str]
    APP_URL: ENC[AES256_GCM,data:5b8TXhJKkoj2PA6t+ZrXVNlW2nMZGGdLY9sKyxPUqj5+G9xuAFy9jv3MpyP914dAm0mbSzNSYm35VXvvd0HETB60ODM=,iv:8KV0fkpxuXy4g493OzHP5wBEBAs58QSTzAa5cPnN05E=,tag:WrwMj6ZrzrqnmTOoxsrV6g==,type:str]
    BCRYPT_ROUNDS: ENC[AES256_GCM,data:SzIdBg==,iv:nRfRZUQhL44yOjmAott8OxecPHVJ6t0ibCwgDJkMdqc=,tag:w4jVDK48D30djbbAdIK2dA==,type:str]
    BROADCAST_CONNECTION: ENC[AES256_GCM,data:TSHWXS/W/UI=,iv:bAYsfdGJUbehIFLb3Pi0JP+j7vQq29mlIGL+TuCGknM=,tag:K0YqniryMY/5QNZq0BLWRg==,type:str]
    CACHE_PREFIX: ""
    CACHE_STORE: ENC[AES256_GCM,data:tyXqJZ9u8h0=,iv:J6ZZh5qlgFRUVzlrkbhE0nB8z4v9KzyzNy9fj8TKhg0=,tag:/ocBDEYTVutcn+j0MW9spA==,type:str]
    CASHIER_CURRENCY: ENC[AES256_GCM,data:f9SOLQ==,iv:Pyez+bN3eAugDutUoFcfod5a5TB3STGE4a1KviKTagU=,tag:7I6dT6A+uFNLghEvdHyNyw==,type:str]
    CASHIER_CURRENCY_LOCALE: ENC[AES256_GCM,data:/gGfN0sRAhA=,iv:KAsWJBzqbdsxMLI3oELgw/Zn1AEVWbU35/5gXzxMnWU=,tag:APGmcxmHu9n14765m9RD5Q==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:FbF/3X+b51Q=,iv:+bCuISgvEaqlfRg4zDwyu1So8v1QDdBzRucPqKLFzr0=,tag:Ui6JpHyLYYaqZ1J6WIbs/w==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:tiySthIXVG8o3c1uQ3ehmA==,iv:yGAKc33MLlUN4wLDJZtnm3UFERPx20H3z09WArUpz7s=,tag:xApYNTTci2p5trypm1npZQ==,type:str]
    DB_HOST: ENC[AES256_GCM,data:2KJqtQVZYmQFG6EZbWYbMRIlgEYK5IgKA1NVy4JL0FaF7xFESM5YhmEezrl436Fq,iv:h8Acp/RnBfX5aqu6Os0ywrdMRMemrE9Mv/QMvPMMHcY=,tag:9fyCnE8kMKAfqzlz+jHYag==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:X17VRgZnlI85hQMvOAa4zA==,iv:ccMHEyOZl1iD4q7oU8vf5oTeOA7nI9XXCux+EnIYOHA=,tag:FjEKdBfZDhDy+vqJEEt0Qw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:SOrb1FjTPaE=,iv:x7oASn1nY4dHjwtV1V/2rp/a0TbCvu7e9rHEow5hhQ4=,tag:6JhMcQZtR1RiEkEj7q/Kjw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:o9nJtvJ4Z3bkPaOF,iv:gtOsfy+LmUbglIYXkIY3Tnte4Bxko2Wl5O+Xm/ywudQ=,tag:nmCM9tuQlTS8y004uCZcDA==,type:str]
    FILESYSTEM_DISK: ENC[AES256_GCM,data:mIYIKdAg8ro=,iv:iJQDNvYg0X8UOG3raapMxw4gl9iZaUKVJhmw+AIQsF4=,tag:C3cJ4aHoXbHc+SP3FtT2SQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:tDmpcd0sRF8SeyiSm3VzDcDpYwlPx/wmxp6grSp5YNGHiVvEQRmqSAo4Jpb4/krkiYbsnoI/2/qmCZVYjEzKTd50c11IMf5K+uiscHm00Vahb3/xmFixTA==,iv:AhBheMqsHmCeDiusOU/T6hxAzwruFgRmNOYLlN2OInE=,tag:/J3w04aI6RdgmPQ+rO7zOw==,type:str]
    LOG_CHANNEL: ENC[AES256_GCM,data:UYk/TEY1+Lc=,iv:w79HvdNW7F6qyAdxXAiDPO36XcZdPUHnTJTMzuP6gQ8=,tag:2nc0GIqXkTkdl96QsuYSTQ==,type:str]
    LOG_DEPRECATIONS_CHANNEL: ENC[AES256_GCM,data:OUAg3LbEToE=,iv:9SCr6mE5EmU5VhOoAjIsPxI1012dqVhta3XzkGML4VQ=,tag:Q7v+kOlNKph9kwFrwB+bFA==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:SscAnSwsodo=,iv:RryA2Hja3H3qdG7aJ/jpYQYr3AY14E2zY7cg9RntvdQ=,tag:xxsT2Mt9WjTbL9acD7TUhQ==,type:str]
    LOG_STACK: ENC[AES256_GCM,data:H67MruVHKZtIRVeIBxRBnUh/aB4=,iv:pGM4Uz4UMTzhDPf9tglZaw/u3JdSIVU/xjxzyZNDd04=,tag:z84I8l8sqUjk0nYQL6KwFg==,type:str]
    LOGO_DEV_TOKEN: ENC[AES256_GCM,data:gqELdszGPZ11bcld/pv2nDvblaeKEj2HA81fD1ZEaSk7HBnx,iv:qxBcWjCcTNSyiTlscAU4+G/9PekZrtCnkYOY6krfeFY=,tag:SGHRy0ofmcBnjkOtj8Zoig==,type:str]
    MAIL_FROM_ADDRESS: ""
    MAIL_FROM_NAME: ""
    MAIL_HOST: ""
    MAIL_MAILER: ENC[AES256_GCM,data:73h7A4PdSYY=,iv:Cp9ZG8HKmiOaz9cMUrOd3jH4T+QpTypkfsHm5Fhh8jM=,tag:SmJzx74OCCIiPVTaaUnLmQ==,type:str]
    MAIL_PASSWORD: ""
    MAIL_PORT: ENC[AES256_GCM,data:Yk7jWA==,iv:ogkTJzigS8RDtt3kbDMAGVoIKDq42kymBAOc0hWwi+E=,tag:wgOyzAQKEcT0reQo4Adagw==,type:str]
    MAIL_USERNAME: ""
    PHP_CLI_SERVER_WORKERS: ENC[AES256_GCM,data:dTDJ2g==,iv:fA44nX5BGupl7AAc72WFMriRDOLcPP3bbsB+ui6asDY=,tag:wlNFomHKLGp1KPwjvOwckw==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:hQVQFHr9hgM=,iv:JQ/84/6WW++JdDt7hKbSp+RDSl3BIfH20hnTgk7d8YI=,tag:BxCz7X1J4/XaeOYD04v1qw==,type:str]
    REDIS_CLIENT: ENC[AES256_GCM,data:ZkJnT0N7dhHZ9rjp,iv:Tu1duFHRJzP+oX2RnH7OifXKSR9StMt+mWCjRMsnKpw=,tag:qWfyjGggZ7Gerhs8Fgm4NQ==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:iSLziUyjnK/fa/eD4qBDvH3NHTJr/S34ZfZyfMh18bK48lA6MXmoJETpmY8=,iv:sI6UzALJEiR4IAUbNhWwFY6oM7UMbYhlnyElCQedavQ=,tag:jF+aXuGT468pnmNS7GkQYg==,type:str]
    REDIS_PASSWORD: null
    REDIS_PORT: ENC[AES256_GCM,data:SOOm01t7tlw=,iv:KqC4D3xMLVmqAxaAy1zkYY72Ho60R6R72Py5DQps6Po=,tag:KYKM2o3J4BTAI9Ta9ThbKw==,type:str]
    REDIS_PREFIX: ENC[AES256_GCM,data:4Rf+aA==,iv:JNXIEwB/LnTs46hyNAZmSa2iCCsuQz1LJ5hp1LhdmBM=,tag:EKuDysI8TifLsPvNdx8rGA==,type:str]
    SESSION_DOMAIN: ENC[AES256_GCM,data:cnQkwrfgp7w=,iv:vOhLhY56mlgr0iC39uxGThX5Thm0CkbWk7y/WXuCT9U=,tag:VXvZdSKknN7FSqvp43KzIQ==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:ayzGb9TFMC4=,iv:InV+/qQNsFUUpdwLsJbC3TMEWr4XL0KTLJUikK3nVRk=,tag:Eaf+LEZNiB8aWWDW+dpQzw==,type:str]
    SESSION_ENCRYPT: ENC[AES256_GCM,data:iscmMyP/Ztc=,iv:BcRIls1VNClOPeDfeCIl6qJpDKnVLXhPRmWdCeTlIqM=,tag:ze10jzHjh/9d9empmjK6WQ==,type:str]
    SESSION_LIFETIME: ENC[AES256_GCM,data:SANgnQ==,iv:so8bNoYQ2Rpo5ChErJGxxHOGoGnahnaRWlL7Hau4k48=,tag:6cvb1cpjMboblcBtnDTCVg==,type:str]
    SESSION_PATH: ENC[AES256_GCM,data:e6nuAQ==,iv:k3SBOSePIkDgZ257aURHO3NDC0TDxoNIilQsbHFpzoY=,tag:cGWty7PpZYUw/4oGGL3uiQ==,type:str]
kind: Secret
metadata:
    name: uber-api-secret
sops:
    age:
        - recipient: age1ann3qhr9jkn9m8y3tkl8qwg6ederfanhtdqk8g2x5893548wt9ls6877ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdkhSTW5xdFJHQXdmUjhx
            Ynp1dndHa3d0MlU1QXlCUnR1ejdwYUY4ekhBCkx2MXZ6d1pvMExZTzFVNlhuRlZp
            MkE2d2g2MjdmdDg2MDFBb3ptbEs3YkUKLS0tIDhhYjljZG1sN3Z3U1RhOG10WjdQ
            bUZWMDR3N3gremNxM243d2VPaEdSUTAK9wY2CAxmUkBmiIAJ1VWF0BsujOV+hsHx
            aiN7nfd19lBQnybEopWpYTLjHcHFHpQM4LCpeIuCNFZ1JVvLxXzUlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rnvd2ad92af4p70ap6wvevjuhstt9k9ucdrzz5v9pd03wu30uacs3f7v60
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkemYrWHNUYXJKaXZjK2hI
            MG45bUQxTXZEdFY4cVpuZDdvK1d5ZjhhOUJVCkQ0MjNIdUN6QnU5UklWUUlCb241
            ZnI0ZU1vTVhqQ2lVL2loV3VXQ1NyYjgKLS0tIHg1b3dqR1BaRFByL1ZoTFlOWDR6
            aG1BNU5wekJGSFE5cmdMZmdxVGNpbFEKPxBlSgQA4vbs1ft/u2xXv95Ze2jDibJC
            DEfxYRGt74RNojASH9qztQavO3zRqJcQAqIMImAwVjiBFickP8U9mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T07:16:47Z"
    mac: ENC[AES256_GCM,data:1xe1M/f8ZgJwsjKIxhK5fRdeW0wcUliNG0vuJEt/It70K4Pv5VJh5iK+XL5mCnvmq2tJzl2KBoWVq1vkrnAO5S89yyJAzweZCY3rwMeBtUv7lOe7aJF5IC+k/AVfD/CiarkLhtIUpKJqCeI/eP+iEJwz1Ge3a/cdxjYphzKmX4U=,iv:E1NJfwGmZfAMxG20+xj3PO3IQZtjW5i9s01UU+UW65Y=,tag:xvuqeOmqDu8KW1cxJDSo6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
